services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8145:8000"
    environment:
      - HRIS_API_URL=https://pnc.indekstat.cloud
    volumes:
      - ./backend/project_tracking.db:/app/project_tracking.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3145:3000"
    restart: always
    depends_on:
      - backend
